// @generated by scripts/gen_module_tree.py — DO NOT EDIT BY HAND.
#![allow(
    unused_imports,
    dead_code,
    clippy::all,
    warnings,
    unused_qualifications
)]

pub mod analytics;
pub mod deposit;
pub mod guard;
pub mod lifecycle;
pub mod withdraw;
pub mod zipper;
