// @generated by scripts/gen_module_tree.py — DO NOT EDIT BY HAND.
#![allow(
    unused_imports,
    dead_code,
    clippy::all,
    warnings,
    unused_qualifications
)]

include!("../../../../gen/buffa/chain.guard.v1.rs");
