// @generated by scripts/gen_module_tree.py — DO NOT EDIT BY HAND.
#![allow(
    unused_imports,
    dead_code,
    clippy::all,
    warnings,
    unused_qualifications
)]

pub mod auth;
pub mod chain;
pub mod collab;
pub mod fees;
pub mod layout;
pub mod ledger;
pub mod marketdata;
pub mod marketoverview;
pub mod orderbook;
pub mod orders;
pub mod polychart;
pub mod polyester;
pub mod ratelimit;
pub mod tradews;
pub mod transfer;
pub mod triggers;
pub mod vip;
