// @generated by scripts/gen_module_tree.py — DO NOT EDIT BY HAND.
#![allow(
    unused_imports,
    dead_code,
    clippy::all,
    warnings,
    unused_qualifications
)]

include!("../../../../gen/connect/chain.analytics.v1.rs");
