//! Proto → SDK model decoders (Go `codecs/decode` parity).

mod address_book;
mod admin;
mod auth;
mod balances;
mod common;
mod deposit_withdraw;
mod enums;
mod fees;
mod guard_signer;
mod lifecycle;
mod market_data;
mod market_overview;
mod money;
mod orderbook;
mod orders;
mod policies;
mod ratelimit;
mod realtime;
mod sub_accounts;
mod trading_rate_limits;
mod triggers;
mod vip;
mod zipper;

pub use address_book::*;
pub use admin::*;
pub use auth::*;
pub use balances::*;
pub use common::*;
pub use deposit_withdraw::*;
pub use enums::*;
pub use fees::*;
pub use guard_signer::*;
pub use lifecycle::*;
pub use market_data::*;
pub use market_overview::*;
pub use money::*;
pub use orderbook::*;
pub use orders::*;
pub use policies::*;
pub use ratelimit::*;
pub use realtime::*;
pub use sub_accounts::*;
pub use trading_rate_limits::*;
pub use triggers::*;
pub use vip::*;
pub use zipper::*;
